"use client"
import localFont from "next/font/local";
import "./globals.css";
import {createTheme, CssBaseline, ThemeProvider} from "@mui/material";
import {NavBar} from "@/components/NavBar/NavBar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
});

export const colorTheme = createTheme({
  palette: {
    mode: 'dark',
    background: {
      main: '#2C2B28',
    },
    darkGrey: {
      main: '#272623',
    },
    lightGrey: {
      main: '#393937',
    },
    orange: {
      main: '#A3512B',
    },
    text: {
      primary: '#E5E5E2',
      secondary: '#7B6DBB',
    },
  },
});

export default function RootLayout({children}) {

  return (
    <ThemeProvider theme={colorTheme}>
      <CssBaseline/>
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      {children}
      <NavBar></NavBar>
      </body>
      </html>
    </ThemeProvider>

  );
}
